insert into restaurants (id, name, food_type, address, phone, zone, zip, website, image_url)
values
('lily-asian-cuisine', 'Lily Asian Cuisine Sushi & Grill', 'Sushi / Asian', '104 W State St, Kennett Square', '610-925-3700', 'kennett-square', '19348', 'https://www.lilysushiandgrill.com/', '/restaurants/lily-asian-cuisine/hero.jpg'),
('talulas-table', 'Talula''s Table', 'Market / New American', '102 W State St, Kennett Square', '610-444-8255', 'kennett-square', '19348', 'https://www.talulastable.com/', '/restaurants/talulas-table/hero.jpg'),
('la-verona', 'La Verona', 'Italian', '114 E State St, Kennett Square', '610-444-2244', 'kennett-square', '19348', 'https://laveronapa.com/', '/restaurants/la-verona/hero.jpg'),
('portabellos', 'Portabellos', 'Italian / Seafood', '108 E State St, Kennett Square', '610-925-4984', 'kennett-square', '19348', 'https://www.portabellosofkennettsquare.com/', '/restaurants/portabellos/hero.jpg'),
('sweet-amelias', 'Sweet Amelia''s', 'New American', '102 E State St, Kennett Square', '484-732-7943', 'kennett-square', '19348', 'https://www.sweetamelias.com/', '/restaurants/sweet-amelias/hero.svg'),
('lettys-tavern', 'Letty''s Tavern', 'Tavern / American', '201 E State St, Kennett Square', '610-444-5688', 'kennett-square', '19348', 'https://www.lettystavern.com/', '/restaurants/lettys-tavern/hero.jpg'),
('michoacana-grill', 'Michoacana Grill', 'Mexican', '201 S Union St, Kennett Square', '610-444-8979', 'kennett-square', '19348', 'https://michoacanagrillkennett.com/', '/restaurants/michoacana-grill/hero.jpg'),
('la-michoacana-ice-cream', 'La Michoacana Homemade Ice Cream', 'Dessert', '231 E State St, Kennett Square', '610-444-2996', 'kennett-square', '19348', null, '/restaurants/la-michoacana-ice-cream/hero.svg'),
('taqueria-guadalajara-express', 'Taqueria Guadalajara Express', 'Mexican', '520 S Union St, Kennett Square', null, 'kennett-square', '19348', null, '/restaurants/taqueria-guadalajara-express/hero.svg'),
('el-ranchero', 'El Ranchero Mexican Restaurant', 'Mexican', '305 W State St #3, Kennett Square', '610-925-0122', 'kennett-square', '19348', null, '/restaurants/el-ranchero/hero.svg'),
('sams-sub-shop', 'Sam''s Sub Shop', 'Subs / Sandwiches', '329 E State St, Kennett Square', '610-444-3580', 'kennett-square', '19348', null, '/restaurants/sams-sub-shop/hero.svg'),
('mary-pats-provisions', 'Mary Pat''s Provisions', 'Breakfast / Cafe', 'Market at Liberty Place, Kennett Square', '484-280-8297', 'kennett-square', '19348', null, '/restaurants/mary-pats-provisions/hero.svg'),
('kaboburritos', 'Kaboburritos', 'Mexican / Mediterranean', 'Market at Liberty Place, Kennett Square', '610-880-6074', 'kennett-square', '19348', null, '/restaurants/kaboburritos/hero.svg'),
('mezzaluna-ksq', 'Mezzaluna KSQ', 'Pizza', '216 S Mill Rd, Kennett Square', '610-263-9919', 'kennett-square', '19348', 'https://mezzalunaksq.com/', '/restaurants/mezzaluna-ksq/hero.png'),
('antonias-pizzeria', 'Antonia''s Pizzeria', 'Pizza', '473 E South St, Kennett Square', '610-448-6245', 'kennett-square', '19348', null, '/restaurants/antonias-pizzeria/hero.svg'),
('pats-pizza-kennett-square', 'Pat''s Pizza Kennett Square', 'Pizza', '350 Scarlet Rd, Kennett Square', '610-444-9007', 'kennett-square', '19348', 'https://www.patspizza.com/', '/restaurants/pats-pizza-kennett-square/hero.svg'),
('sang-tong-thai', 'Sang Tong Thai', 'Thai', '420 W Cypress St, Kennett Square', '610-925-2828', 'kennett-square', '19348', null, '/restaurants/sang-tong-thai/hero.svg'),
('breakfast-bravo', 'Breakfast Bravo', 'Breakfast / American', '420 W Cypress St, Kennett Square', '610-925-2828', 'kennett-square', '19348', null, '/restaurants/breakfast-bravo/hero.svg'),
('the-naked-olive', 'The Naked Olive', 'Mediterranean', '759 W Cypress St, Kennett Square', '610-444-2424', 'kennett-square', '19348', 'https://www.thenakedolive.com/', '/restaurants/the-naked-olive/hero.png'),
('floga-bistro', 'Floga Bistro', 'Italian / Pizza / Mediterranean', '826 E Baltimore Pike, Kennett Square', '610-444-6500', 'kennett-square', '19348', 'https://flogabistro.com/', '/restaurants/floga-bistro/hero.jpg'),
('china-garden', 'China Garden', 'Chinese', '826 E Baltimore Pike, Kennett Square', '610-444-5989', 'kennett-square', '19348', null, '/restaurants/china-garden/hero.svg'),
('hearth-kitchen', 'Hearth Kitchen', 'Mediterranean / Pizza', '847 E Baltimore Pike, Kennett Square', '484-732-8320', 'kennett-square', '19348', null, '/restaurants/hearth-kitchen/hero.svg'),
('applebees-kennett', 'Applebee''s', 'Chain / American', '815 E Baltimore Pike, Kennett Square', '610-444-8092', 'kennett-square', '19348', 'https://www.applebees.com/', '/restaurants/applebees-kennett/hero.svg'),
('buddys-burgers', 'Buddy''s Burgers, Breasts & Fries', 'Burgers / Chicken', '811 E Baltimore Pike, Kennett Square', '484-732-8072', 'kennett-square', '19348', null, '/restaurants/buddys-burgers/hero.svg'),
('capriottis-kennett', 'Capriotti''s Sandwich Shop', 'Sandwiches', '877 E Baltimore Pike, Kennett Square', '610-444-4475', 'kennett-square', '19348', 'https://capriottis.com/', '/restaurants/capriottis-kennett/hero.svg'),
('jersey-mikes-kennett', 'Jersey Mike''s Subs', 'Sandwiches', '817 E Baltimore Pike, Kennett Square', '484-734-1001', 'kennett-square', '19348', 'https://www.jerseymikes.com/', '/restaurants/jersey-mikes-kennett/hero.webp'),
('caffe-pura', 'Caffè Pura', 'Cafe', '210 S Mill Rd, Kennett Square', '484-753-7607', 'kennett-square', '19348', null, '/restaurants/caffe-pura/hero.svg'),
('chaikhana-chai', 'Chaikhana Chai', 'Cafe / Tea', '227 Birch St, Kennett Square', '610-644-0829', 'kennett-square', '19348', null, '/restaurants/chaikhana-chai/hero.svg'),
('the-creamery', 'The Creamery', 'Beer garden / food', '401 Birch St, Kennett Square', '484-732-7040', 'kennett-square', '19348', 'https://www.thecreameryatkennettsquare.com/', '/restaurants/the-creamery/hero.svg'),
('la-bamba', 'La Bamba', 'Ice cream / snacks', '739 W Cypress St, Kennett Square', '610-925-2805', 'kennett-square', '19348', null, '/restaurants/la-bamba/hero.svg'),
('deisys-cake-shop', 'Deisy''s Cake Shop', 'Bakery / Desserts', '315 W State St, Kennett Square', '610-444-1419', 'kennett-square', '19348', null, '/restaurants/deisys-cake-shop/hero.svg'),
('las-alondras-bakery', 'Las Alondras Bakery', 'Bakery', '113 W State St, Kennett Square', '610-444-3966', 'kennett-square', '19348', null, '/restaurants/las-alondras-bakery/hero.svg'),
('hangry-bear-creamery', 'Hangry Bear Creamery', 'Ice cream', '660 E Cypress St, Kennett Square', '610-744-2722', 'kennett-square', '19348', null, '/restaurants/hangry-bear-creamery/hero.svg'),
('archies', 'Archie''s', 'Sandwiches', '1670 Newark Rd, Kennett Square', '610-268-0616', 'kennett-square', '19348', null, '/restaurants/archies/hero.svg'),
('sovana-bistro', 'Sovana Bistro', 'Restaurant', '696 Unionville Rd, Kennett Square', '610-444-5600', 'kennett-square', '19348', 'https://www.sovanabistro.com/', '/restaurants/sovana-bistro/hero.png'),
('farmer-and-co', 'Farmer & Co', 'Coffee / Cafe', 'Unionville', '610-347-0209', 'kennett-square', '19348', null, '/restaurants/farmer-and-co/hero.svg'),
('lilianas-pizza-grill', 'Liliana''s Pizza & Grill', 'Pizza', '1160 Newark Rd, Toughkenamon', '484-915-2121', 'toughkenamon-avondale', '19348', null, '/restaurants/lilianas-pizza-grill/hero.svg'),
('deannas', 'Deanna''s', 'Mexican / Grocery food', '1185 Newark Rd, Toughkenamon', '610-268-8797', 'toughkenamon-avondale', '19348', null, '/restaurants/deannas/hero.svg'),
('taquito-feliz', 'Taquito Feliz', 'Mexican / Food truck', '1803 Baltimore Pike, Avondale', '484-720-8530', 'toughkenamon-avondale', '19348', null, '/restaurants/taquito-feliz/hero.svg'),
('taquitos-magy', 'Taquitos Magy', 'Mexican', '1056 Gap Newport Pike, Avondale', '484-667-1348', 'toughkenamon-avondale', '19348', null, '/restaurants/taquitos-magy/hero.svg'),
('taqueria-moroleon', 'Taqueria Moroleon', 'Mexican', '9173 Gap Newport Pike, Avondale', '610-268-3066', 'toughkenamon-avondale', '19348', null, '/restaurants/taqueria-moroleon/hero.svg'),
('bravo-pizza-avondale', 'Bravo Pizza of Avondale', 'Pizza / Italian', '817 Gap Newport Pike, Avondale', '610-268-0808', 'toughkenamon-avondale', '19348', null, '/restaurants/bravo-pizza-avondale/hero.svg'),
('sake-hana', 'Sake Hana', 'Sushi / Japanese', '801 Gap Newport Pike, Avondale', '610-268-2889', 'toughkenamon-avondale', '19348', null, '/restaurants/sake-hana/hero.svg'),
('perkins-avondale', 'Perkins', 'Breakfast / American', '954 Gap Newport Pike, Avondale', '610-268-3513', 'toughkenamon-avondale', '19348', 'https://www.perkins.com/', '/restaurants/perkins-avondale/hero.svg'),
('taco-bell-avondale', 'Taco Bell', 'Fast food', '764 Gap Newport Pike, Avondale', '610-268-2458', 'toughkenamon-avondale', '19348', 'https://www.tacobell.com/', '/restaurants/taco-bell-avondale/hero.png'),
('earls-sub-shop', 'Earl''s Sub Shop', 'Subs', '79 W State St, Avondale', '610-268-2123', 'toughkenamon-avondale', '19348', null, '/restaurants/earls-sub-shop/hero.svg'),
('twelves-grill-cafe', 'Twelves Grill & Cafe', 'American', '10 Exchange Pl, West Grove', '610-869-4020', 'west-grove', '19348', 'https://www.twelvesgrill.com/', '/restaurants/twelves-grill-cafe/hero.jpg'),
('stubborn-goat-brewing', 'Stubborn Goat Brewing', 'Brewpub / food', '122 Rosehill Ave, West Grove', '610-679-9017', 'west-grove', '19348', 'https://www.stubborngoatbrewing.com/', '/restaurants/stubborn-goat-brewing/hero.svg'),
('china-kitchen-west-grove', 'China Kitchen', 'Chinese', '119 Rosehill Ave, West Grove', '610-869-2211', 'west-grove', '19348', null, '/restaurants/china-kitchen-west-grove/hero.svg'),
('aurora-pizzeria', 'Aurora Pizzeria & Pasta Kitchen', 'Pizza / Italian', '27 Jenners Village Ctr, West Grove', '610-869-8811', 'west-grove', '19348', null, '/restaurants/aurora-pizzeria/hero.svg'),
('corner-cafe-west-grove', 'Corner Cafe', 'Breakfast / Cafe', '827A W Baltimore Pike, West Grove', '610-869-5557', 'west-grove', '19348', null, '/restaurants/corner-cafe-west-grove/hero.svg'),
('zen-modern-asian', 'Zen Modern Asian Kitchen', 'Asian Fusion', '829 W Baltimore Pike, West Grove', '610-646-0062', 'west-grove', '19348', null, '/restaurants/zen-modern-asian/hero.svg'),
('fajitas-y-salsa', 'Fajitas Y Salsa', 'Mexican', '55 Jenners Village, West Grove', '610-229-9094', 'west-grove', '19348', null, '/restaurants/fajitas-y-salsa/hero.svg'),
('mcdonalds-west-grove', 'McDonald''s', 'Fast food', '859 W Baltimore Pike, West Grove', '610-345-1566', 'west-grove', '19348', 'https://www.mcdonalds.com/', '/restaurants/mcdonalds-west-grove/hero.jpg'),
('panaderia-estrella', 'Panaderia Estrella', 'Bakery / Coffee', '123 Rosehill Dr, West Grove', '610-869-8122', 'west-grove', '19348', null, '/restaurants/panaderia-estrella/hero.svg'),
('new-dragon-hockessin', 'New Dragon Restaurant', 'Chinese', '707 Ace Memorial Dr, Hockessin', '302-235-2737', 'hockessin', '19707', null, '/restaurants/new-dragon-hockessin/hero.svg'),
('back-burner', 'Back Burner Restaurant', 'American', '425 Hockessin Corner, Hockessin', '302-239-2314', 'hockessin', '19707', 'https://www.backburner.com/', '/restaurants/back-burner/hero.png'),
('redfire-grill', 'Redfire Grill & Steakhouse', 'Steakhouse', '400 Lantana Dr, Hockessin', '302-235-2600', 'hockessin', '19707', null, '/restaurants/redfire-grill/hero.svg'),
('letties-kitchen', 'Lettie''s Kitchen', 'American / Chicken', '1318 Old Lancaster Pike, Hockessin', '302-239-7816', 'hockessin', '19707', null, '/restaurants/letties-kitchen/hero.svg'),
('mexican-table', 'Mexican Table', 'Mexican', '7288 Lancaster Pike, Hockessin', '302-239-5590', 'hockessin', '19707', null, '/restaurants/mexican-table/hero.svg'),
('corner-cove', 'Corner Cove Restaurant & Bar', 'Pizza / Seafood / Bar', '410 Hockessin Corner, Hockessin', '302-235-8320', 'hockessin', '19707', null, '/restaurants/corner-cove/hero.svg'),
('harpers-asian-bistro', 'Harper''s Asian Bistro', 'Asian Fusion / Sushi', '228 Lantana Dr, Hockessin', '302-215-7094', 'hockessin', '19707', null, '/restaurants/harpers-asian-bistro/hero.svg'),
('primas-pizza-pasta', 'Prima''s Pizza & Pasta', 'Pizza', '7454 Lancaster Pike, Hockessin', '302-239-3522', 'hockessin', '19707', null, '/restaurants/primas-pizza-pasta/hero.svg'),
('perfect-cup-cafe', 'The Perfect Cup Cafe', 'Cafe / Breakfast', '7460 Lancaster Pike, Hockessin', '302-239-9118', 'hockessin', '19707', null, '/restaurants/perfect-cup-cafe/hero.svg'),
('bachetti-bros', 'Bachetti Bros', 'Italian deli / catering', 'Wilmington, near Hockessin', '302-994-4467', 'hockessin', '19707', null, '/restaurants/bachetti-bros/hero.svg'),
('soybean-asian-grille', 'Soybean Asian Grille', 'Thai / Chinese / Asian', 'Wilmington, near Hockessin', '302-636-0800', 'hockessin', '19707', null, '/restaurants/soybean-asian-grille/hero.svg'),
('antica-italian', 'Antica Italian Restaurant', 'Italian', '1623 Baltimore Pike, Chadds Ford', '484-770-8631', 'chadds-ford', '19317', 'https://www.antica-restaurant.com/', '/restaurants/antica-italian/hero.svg'),
('agave-mexican', 'Agave Mexican Cuisine', 'Mexican', '1620 Baltimore Pike, Chadds Ford', '484-770-8345', 'chadds-ford', '19317', 'https://www.agaveofchaddsford.com/', '/restaurants/agave-mexican/hero.svg'),
('hanks-place', 'Hank''s Place', 'American / Breakfast', 'Chadds Ford', null, 'chadds-ford', '19317', 'https://www.hanksplace.com/', '/restaurants/hanks-place/hero.svg'),
('the-gables-chadds-ford', 'The Gables at Chadds Ford', 'American', '423 Baltimore Pike, Chadds Ford', null, 'chadds-ford', '19317', 'https://www.thegablesatchaddsford.com/', '/restaurants/the-gables-chadds-ford/hero.png'),
('northbrook-marketplace', 'Northbrook MarketPlace', 'Deli / Breakfast / Desserts', 'West Chester / Unionville area', '610-793-1210', 'chadds-ford', '19317', null, '/restaurants/northbrook-marketplace/hero.svg'),
('the-whip-tavern', 'The Whip Tavern', 'British / Pub', 'Coatesville area', '610-383-0600', 'chadds-ford', '19317', 'https://www.thewhippub.com/', '/restaurants/the-whip-tavern/hero.svg'),
('the-pear', 'The Pear', 'New American', 'Dilworthtown / West Chester area', '484-260-1425', 'chadds-ford', '19317', null, '/restaurants/the-pear/hero.svg'),
('daddys-kitchen', 'Daddy''s Kitchen', 'Breakfast / American', 'Landenberg', '610-255-4009', 'chadds-ford', '19317', null, '/restaurants/daddys-kitchen/hero.svg'),
('the-haven-social', 'The Haven Social', 'Restaurant', 'Landenberg', '610-255-4879', 'chadds-ford', '19317', null, '/restaurants/the-haven-social/hero.svg')
on conflict (id) do update set
  name = excluded.name,
  food_type = excluded.food_type,
  address = excluded.address,
  phone = excluded.phone,
  zone = excluded.zone,
  zip = excluded.zip,
  website = excluded.website,
  image_url = excluded.image_url;